[tool.poetry]
name = "cna_mixture"
version = "0.1.0"
description = ""
authors = ["M. J. Wilson"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.11.3"
maturin = "^1.1.0"
numpy = "^1.26.0"
matplotlib = "*"
scipy = "*"
scikit-learn = "*"
